c-category
yoshiaki-numajiri/202202codeups_team-project pull request #14
Opened 2022-02-13 09:37 UTC by Hi-web-design

_c-category.ejs
_c-category.scss
追記しました

2022-02-13 11:02 UTC, yoshiaki-numajiri requested changes
_category.ejs

①”all”カテゴリのスタイルですが、”all”のカテゴリが固定でこのスタイルなのではなく、
クリックされて選択されているカテゴリがこの白色のスタイルなのだと思います。
jQueryなどで制御できるように、白色になるスタイルは分けてはどうでしょう？
<li class="c-category__item is-active“>
のような感じで。


② 使いまわすことを前提とすると、aタグの中身は固定値じゃない方がよいと思います。
     <a href="<%= link %>"><%= text %></a>
のようにして、includeする側で、
      <%- include('./component/_c-ca’tegory,{text:’カテゴリ1’, link:'#'}) %>
のように値を渡すようにしてはどうでしょう？

_category.scss

上記①の理由で、
.c-category__item--allのセレクターを
.c-category__item.is-activeのようなスタイルにしてはどうでしょう？

_index.ejs

このファイルが更新されちゃってますね。よく確認したら、c-top-btnのときにも更新されてますね。

2022-02-13 11:52 UTC, Hi-web-design commented
①の件、修正に少し時間ください

_index.ejsの更新は表示確認で貼り付けたものの消し忘れです

2022-02-15 11:09 UTC, Hi-web-design commented
c-category.ejs→p-category.ejsに変更
c-category.scss→p-category.scssに変更
script.jsに追記

2022-02-15 12:43 UTC, yoshiaki-numajiri commented
_p-category.ejs
・デフォルトでallのliにはis-activeクラスをつけておいたらどうでしょう？
・l-innerはinclude元で書いた方がよい気がしますが、いかがでしょう？
（ゆうきさんのご意見も伺いたい）

index.ejs
・こちらはプッシュしないようにできますか？

2022-02-15 13:43 UTC, yoshiaki-numajiri commented
>中でインナー調節する分には問題ないです。
ただ以下のように書いた方がクラス名の関係性が取れて良いですね。
<div class="p-category__inner l-inner">

なるほど。
メイン的な部分の中身についてカテゴリやカード、ページネーションなどそれぞれ個別にインナーを入れてもいいし、まとめて入れてもどちらでもいいってことですよね？

こちらのコメントって、このブランチを削除すると見れなくなっちゃいますかね？

2022-02-15 14:54 UTC, y-knsg1206 commented
>メイン的な部分の中身についてカテゴリやカード、ページネーションなどそれぞれ個別にインナーを入れてもいいし、まとめて入れてもどちらでもいいってことですよね？

p-categoryはセクションの大元のクラスですよね？
p-cardなどにl-inner付けるのは好ましくないです。

>こちらのコメントって、このブランチを削除すると見れなくなっちゃいますかね？

おそらく残るはずです。

2022-02-15 21:52 UTC, yoshiaki-numajiri commented
>p-categoryはセクションの大元のクラスですよね？
p-cardなどにl-inner付けるのは好ましくないです。

すみません。p-cardにl-innerをつけない方がよいことはわかりました。

p-cardsをイメージしてl-innerをつける場合もあるのかなと考えたのですが、
そもそもp-cardsはプロジェクトにせずページ全体のejsファイルの要素と考えるんでしたね。

>メイン的な部分の中身についてカテゴリやカード、ページネーションなどそれぞれ個別にインナーを入れてもいいし、まとめて入れてもどちらでもいいってことですよね？

この部分について、Notionに追加質問させていただきました。

2022-02-19 09:47 UTC, merged