c-section-title
yoshiaki-numajiri/202202codeups_team-project pull request #30
Opened 2022-02-19 12:07 UTC by Hi-web-design

_c-section-jatitle.ejs/.scss→_c-section-title.ejs/.scssに変更
_p-pager.ejsのクラス名をlargerに変更

_c-top-btn.scss下記をコメントアウト
// .c-top-btn {
//   display: block;
//   position: fixed;
//   right: rem(20);
//   bottom: rem(30);
//   z-index: 10;
// }

2022-02-19 12:26 UTC, Hi-web-design commented
_c-logo.scss
.c-logo→.c-logo img

.c-logo img {
  width: rem(70);
  @include mq(md) {
    width: rem(94);
  }
}
としました

2022-02-20 00:23 UTC, yoshiaki-numajiri requested changes
### c-section-title
①h2とpに付与するクラスは、"c-section-title__**"の形がよいと思います。
②"事業内容"や"Content"の部分は、他のセクションでも使いまわせるように変数に置き換えますか？

### c-logo
ヘッダーで使うロゴとフッターで使うロゴはPC表示のときに差があるので、
（SP表示ではヘッダーもフッターも同じ幅ですが、PC表示ではヘッダーのみ大きいです）
ここでは幅をつけずにおくか、modifierを追加して2種類作る必要がありそうです。

どちらかというと、ここでは幅をつけずにp-header__logoなどで幅をつけた方がよいかもしれません。

2022-02-20 00:34 UTC, Hi-web-design commented
c-section-title
①h2とpに付与するクラスは、"c-section-title__**"の形がよいと思います。
→c-section-title__ja,c-section-title__enに変更します

②"事業内容"や"Content"の部分は、他のセクションでも使いまわせるように変数に置き換えますか？
→そうしたいのですが変数の理解が乏しいので...ちょっとやってみます

c-logo
ヘッダーで使うロゴとフッターで使うロゴはPC表示のときに差があるので、
（SP表示ではヘッダーもフッターも同じ幅ですが、PC表示ではヘッダーのみ大きいです）
ここでは幅をつけずにおくか、modifierを追加して2種類作る必要がありそうです。

どちらかというと、ここでは幅をつけずにp-header__logoなどで幅をつけた方がよいかもしれません。
→c-logoにはcssは当てないようにします

2022-02-20 01:12 UTC, Hi-web-design commented
c-section-title__ja,c-section-title__enに変更

"事業内容"や"Content"の部分を変数に置き換え

c-logoに戻してcss削除

2022-02-20 01:28 UTC, merged