c-logo.ejs
yoshiaki-numajiri/202202codeups_team-project pull request #4
Opened 2022-02-10 11:55 UTC by Hi-web-design

_c-logo.ejs
_c-logo.scss
images/commonにlogo.svg
上記を追記しました。

2022-02-10 13:51 UTC, yoshiaki-numajiri requested changes
3点気になることがあります。

①こちらのコンポーネントはaタグにしてリンクもセットでつけませんか？
②ブレイクポイントの変数ですが、元と"DartSass_EJS"で設定されている"md"を使いませんか？
③z-indexの指定ですが、コンポーネントに余白をつけないことと同じ理由で、別のところにつけた方がよい気がします。

①と③については迷いながらコメントしていて、ゆうきさんの助言もいただきたいなと思っています。

2022-02-11 01:39 UTC, yoshiaki-numajiri commented
お待たせしてしまってすみません。保留にしていた部分ですが、

①aタグをコンポーネントに
②tab → mdへ
③z-index削除（後ほどp-header.scss内で.p-header__logoに指定がよいと思っています）
④widthはこのままで

修正理由はチームよしとし共有資料の
質問 ▶︎ EJS、FLOCSSについて ▶︎コンポーネントの分け方について “CodeUps”のロゴを例に
でゆうきさんに質問していて、そちらのやりとりを確認していただけます。

2022-02-11 11:35 UTC, Hi-web-design commented
クラス名をaタグに付け直しました。

2022-02-11 11:39 UTC, merged

2022-02-11 11:40 UTC, yoshiaki-numajiri commented
ありがとうございました^_^