p-footer-nav padding変更
yoshiaki-numajiri/202202codeups_team-project pull request #43
Opened 2022-02-22 11:26 UTC by Hi-web-design

padding-top: rem(8) ;→padding: rem(4) 0;に変更しました

2022-02-22 12:41 UTC, Hi-web-design commented
制作実績と自社メディアを追記しました

2022-02-22 14:10 UTC, yoshiaki-numajiri requested changes
たぶん"自社メディア"と"ブログ"は同じなので、ブログでよいと思います。
デザインカンプを意図的に間違えて、納品時に「ここ違和感を感じたので、こうな感じで直しておきました」と報告するか〜になってますけどどうします？と確認するところなのだと思います。
トップはSP表示のみ、自社メディアはブログの間違えという解釈でよいんじゃないかと思います。

paddingの修正はバッチリでした！

2022-02-23 01:52 UTC, yoshiaki-numajiri commented
top-header.ejsは使わないので、p-header.ejs修正と一緒に削除をお願いできますか？

2022-02-23 08:46 UTC, Hi-web-design commented
自社メディアをブログに変更しました

2022-02-23 10:44 UTC, merged